[package]
name = "faxc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "faxc"
path = "crates/faxc-drv/src/lib.rs"

[[bin]]
name = "faxc"
path = "crates/faxc-drv/src/main.rs"
