[package]
name = "faxc-lir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
faxc-util.workspace = true
faxc-mir.workspace = true
faxc-sem.workspace = true

[dev-dependencies]